USB_VID = 0x1D50
USB_PID = 0xACAB
USB_PRODUCT = "Jumperless V5"
USB_MANUFACTURER = "Architeuthis Flux"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = B
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q128JVxQ"
